INSERT INTO RESHET.ACCOMMODATION (ID_ACC, ID_HOTEL, PRICE, QUANTITY, TYPE) VALUES (1, 4, 500, 3, 'standart');
INSERT INTO RESHET.ACCOMMODATION (ID_ACC, ID_HOTEL, PRICE, QUANTITY, TYPE) VALUES (2, 1, 253, 3, 'lux');
INSERT INTO RESHET.ACCOMMODATION (ID_ACC, ID_HOTEL, PRICE, QUANTITY, TYPE) VALUES (3, 2, 2525, 5, 'standart');
INSERT INTO RESHET.ACCOMMODATION (ID_ACC, ID_HOTEL, PRICE, QUANTITY, TYPE) VALUES (4, 2, 32, 2, 'econ');
INSERT INTO RESHET.ACCOMMODATION (ID_ACC, ID_HOTEL, PRICE, QUANTITY, TYPE) VALUES (5, 4, 524, 4, 'lux');
