INSERT INTO RESHET.HOTEL (ID_HOTEL, NAME_H, LOC_LAT, LOC_LNG, CATEGORY, CITY, COUNTRY) VALUES (4, 'Plaza', 25, 25, 4, 'Kiev', 'Ukraine');
INSERT INTO RESHET.HOTEL (ID_HOTEL, NAME_H, LOC_LAT, LOC_LNG, CATEGORY, CITY, COUNTRY) VALUES (1, 'Hilton', 35.25, 54.35, 5, 'London', 'Britain');
INSERT INTO RESHET.HOTEL (ID_HOTEL, NAME_H, LOC_LAT, LOC_LNG, CATEGORY, CITY, COUNTRY) VALUES (2, 'Selavi', 100, 400, 3, 'Paris', 'France');
INSERT INTO RESHET.HOTEL (ID_HOTEL, NAME_H, LOC_LAT, LOC_LNG, CATEGORY, CITY, COUNTRY) VALUES (25, 'asdasdasdsdf', 1, 0, 1, 'gfhfghfgh', 'fgdfgdfgdfgdf');
INSERT INTO RESHET.HOTEL (ID_HOTEL, NAME_H, LOC_LAT, LOC_LNG, CATEGORY, CITY, COUNTRY) VALUES (23, 'Britania Hotel', 0, 0, 3, 'Kemer', 'Turkey');
INSERT INTO RESHET.HOTEL (ID_HOTEL, NAME_H, LOC_LAT, LOC_LNG, CATEGORY, CITY, COUNTRY) VALUES (24, 'Kazanova Votak Vot', 0, 0, 2, 'Meshelbek city', 'Melshelbek');
INSERT INTO RESHET.HOTEL (ID_HOTEL, NAME_H, LOC_LAT, LOC_LNG, CATEGORY, CITY, COUNTRY) VALUES (41, 'Plaza', 30, 20, 223, 'Gorlovka', 'Ukraine');
INSERT INTO RESHET.HOTEL (ID_HOTEL, NAME_H, LOC_LAT, LOC_LNG, CATEGORY, CITY, COUNTRY) VALUES (28, 'dsfsdfdsfsdfFFFF', 0, 0, 0, 'sdfsdfsdFF', 'sdfsdfsdFFF');
